//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pest1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PestLocation
    {
        public int column_0 { get; internal set; }
        public string Scientific_Name { get; set; }
        public string Vernacular_name { get; set; }
        public string Event_Date__parsed { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}
